/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cenfotec.components.control.drawing;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.Random;

/**
 *
 * @author David Madrigal
 */
public class Graphic extends javax.swing.JPanel {

    /**
     * Creates new form Points
     */
    public Graphic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doDrawing(Graphics g) {
        Random rand = new Random();
        int count = 1;
        Color randomColor = new Color(rand.nextFloat(), rand.nextFloat(), rand.nextFloat());
        float[] dash1 = {2f, 0f, 2f};

        Graphics2D g2d = (Graphics2D) g.create();

        g2d.drawLine(100, 340, 100, 100);
        g2d.drawLine(100, 340, 600, 340);

        BasicStroke bs1 = new BasicStroke(1, BasicStroke.CAP_BUTT,
                BasicStroke.JOIN_ROUND, 1.0f, dash1, 2f);

        BasicStroke bs2 = new BasicStroke(30, BasicStroke.CAP_BUTT,
                BasicStroke.JOIN_BEVEL);

        g2d.setStroke(bs1);
        for (int i = 320; i > 80; i -= 20) {
            g2d.drawString((340 - i) + "", 75, i + 5);
            g2d.drawLine(100, i, 600, i);
        }
        g2d.setStroke(bs2);
        for (int i = 125; i < 600; i += 85) {
            g2d.setPaint(randomColor);
            g2d.drawString("Valor " + count, i, 360);
            g2d.drawLine(i + 20, 340, i + 20, (rand.nextInt(240)) + 100);
            randomColor = new Color(rand.nextFloat(), rand.nextFloat(), rand.nextFloat());
            count++;
        }

        g2d.dispose();
    }

    @Override
    public void paintComponent(Graphics g) {

        super.paintComponent(g);
        doDrawing(g);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
